### ISSUE TITLE
Fix nested dropdown.

### ISSUE THREAD

**Issue by whoodes** [insightbulb/insightbulb#25]
~When you open the dropdown and click on a region, the sub-region and station numbers open up within the same dropdown.  This looks like it is being caused by bootstraps default css not being overridden.~  

**This issue now focuses on making both dropdowns scrollable.**

**Comment by whoodes** [comment]
@dkihe fyi, you might wanna pull and test it out, you might be able to fix this easier than me.

**Comment by dkihe** [comment]
I've fixed the issue of the dropdowns opening in the same box.  The problem is that the outermost `ul` was part of the `scrollable-menu` class.  This causes everything within the `ul` tag to be seen as part of a single scrollable menu including the the inner `ul` tag.

To fix this I simply got rid of the scrollable-menu class:
`<ul class="dropdown-menu  tidal region" role="menu">`

<img width="1440" alt="Screen Shot 2019-03-19 at 4 58 36 PM" src="https://user-images.githubusercontent.com/22701154/54656098-6e5aa800-4a68-11e9-9827-691368b6e3ce.png">

**Comment by dkihe** [comment]
The problem with this issue is that making the menu scrollable with: 
```
.scrollable-menu {
    max-height: 200px;
    overflow-y: auto; 
}
```
causes the next dropdown to appear within the first dropdown list (I think this was the original issue)?  I think this has to do with the way the html is structured and with the location of the `position: relative;` css. 

 If we want two nested scrollable menus it seems the only way to fix this is with jquery.  I'll attampt to fix this using jquery and maybe look for possible alternatives.

**Comment by whoodes** [comment]
Closing this, as @dkihe talked about an alternative approach involving removing regions outside of the US to shorten the list.
